---
title: "EDA and Linear Regression on Housing Prices"
author: "Jeremiah Brown"
date: "2024-01-20"
output: html_document
---

# Define the Problem
### 1. Desired Outcome
The goal of this project is to create a linear regression model that successfully predicts housing prices. 
### 2. Requirements
### 3. General Comments
### 4. Plan of Attack 

## Load Libraries 
```{r include=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(include=TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(GGally)
library(reshape2)
library(glmnet)
library(caret)
library(xgboost)
```


# Load Data

```{r}
train <- read_csv(paste(getwd(),"/Data/train.csv", sep=""))
test <- read_csv(paste(getwd(),"/Data/test.csv", sep=""))
```

# Prepare Data

```{r}
head(train)
```
```{r}
numericCols <- train %>% select(where(is.numeric))
catCols <- train %>% select(!where(is.numeric))
cat(paste("Numeric Columns: ", colnames(numericCols)), "\n\n")
cat(paste("Categorical Columns: ", colnames(catCols)))
```


```{r}
# Removing Id and other categorical variables.
numericCols$Id <- NULL
catCols$MSSubClass <- numericCols$MSSubClass
numericCols$MSSubClass <- NULL
catCols$YrSold <- numericCols$YrSold
numericCols$YrSold <- NULL
catCols$YearBuilt <- numericCols$YearBuilt
numericCols$YearBuilt <- NULL
catCols$YearRemodAdd <- numericCols$YearRemodAdd
numericCols$YearRemodAdd <- NULL
catCols$OverallQual <- numericCols$OverallQual
numericCols$OverallQual <- NULL
catCols$OverallCond <- numericCols$OverallCond
numericCols$OverallCond <- NULL
catCols$MoSold <- numericCols$MoSold
numericCols$MoSold <- NULL
catCols$GarageYrBlt <- numericCols$GarageYrBlt
numericCols$GarageYrBlt <- NULL
catCols$GarageCars <- numericCols$GarageCars
numericCols$GarageCars <- NULL
catCols$FirePlaces <-numericCols$Fireplaces
numericCols$Fireplaces <- NULL
catCols$TotRmsAbvGrd <- numericCols$TotRmsAbvGrd
numericCols$TotRmsAbvGrd <- NULL
catCols$BedroomAbvGr <- numericCols$BedroomAbvGr
numericCols$BedroomAbvGr <- NULL
catCols$KitchenAbvGr <- numericCols$KitchenAbvGr
numericCols$KitchenAbvGr <- NULL
numericCols$SalePrice <- NULL
```

```{r}
#Replacing missing numeric values
for (n in colnames(numericCols)){
    numericCols[, n] <- numericCols %>% select(all_of(n)) %>% mutate(!!sym(n) := ifelse(is.na(!!sym(n)), median(!!sym(n), na.rm = TRUE), !!sym(n)))
}
```

```{r}
# Combining numeric features
numericCols <- numericCols %>% mutate(TotalBaths = BsmtFullBath * .5 + HalfBath * .5 + BsmtFullBath + FullBath)
numericCols$BsmtFullBath <- NULL; numericCols$BsmtHalfBath <- NULL; numericCols$HalfBath <- NULL; 
numericCols$FullBath <- NULL
numericCols <- numericCols %>% mutate(TotalSF = `TotalBsmtSF` + `1stFlrSF` + `2ndFlrSF` + GrLivArea + LowQualFinSF)
numericCols$BsmtFinSF1 <- NULL; numericCols$BsmtFinSF2 <- NULL; numericCols$BsmtUnfSF <- NULL; 
numericCols$LowQualFinSF <- NULL; numericCols$GrLivArea <- NULL
numericCols$TotalBsmtSF <- NULL; numericCols$"1stFlrSF" <- NULL; numericCols$"2ndFlrSF" <- NULL
numericCols <- numericCols %>% mutate(OutdoorSF = WoodDeckSF + OpenPorchSF + EnclosedPorch + `3SsnPorch` + ScreenPorch)
numericCols$WoodDeckSF <- NULL; numericCols$OpenPorchSF <- NULL; numericCols$EnclosedPorch <- NULL
numericCols$"3SsnPorch" <- NULL; numericCols$ScreenPorch <- NULL
```

```{r}
calc_mode <- function(tb){
  mode_val <- tb %>% group_by(colnames(tb)[1]) %>% arrange(desc(colnames(tb)[1]))
  if (is.na(mode_val[[colnames(tb)[1]]][1])){
    if(is.list(mode_val[[colnames(tb)[2]]])){
      return (sapply(mode_val[[colnames(tb)[2]]]), toString)
    }
    return (mode_val[[colnames(tb[1])]][2])
  } 
  return (mode_val[[colnames(tb)]][1])
}

```

```{r}
#Replacing missing categorical values
remaining_cols <- list()
for (n in colnames(catCols)){
  mode_val <- md <- catCols %>% select(n) %>% group_by(!!sym(n)) %>% summarize(count = n()) %>% arrange(desc(count)) %>% select(n)
  if ((!is.na(mode_val[[n]][1])) && (is.character(mode_val[[n]][1]))){
    catCols[, n] <- catCols %>% select(all_of(n)) %>% mutate(!!sym(n) := ifelse(is.na(!!sym(n)), mode_val, !!sym(n)))
  } else if (!is.na(mode_val[[n]][1]) && is.numeric(mode_val[[n]][1])){
    mode_val <- calc_mode(catCols[, n])
    catCols[, n] <- catCols %>% select(all_of(n)) %>% mutate(!!sym(n) := ifelse(is.na(!!sym(n)), mode_val, !!sym(n)))
  } else {
    remaining_cols <- append(remaining_cols, n)
  }
}

for (n in colnames(catCols)){
  if (n %in% remaining_cols){
    catCols[, n] <- NULL
  }
}
```

```{r}
t <- bind_cols(numericCols, catCols)
for (n in colnames(t)){
  if (is.list(t[[n]])){
    t[, n] <- NULL
  }
}

```

```{r}
#Traning Linear Model
train_data <-as.matrix(t)
fit_lasso <- cv.glmnet(train_data, train$SalePrice, alpha=1)
predictions <- predict(fit_lasso, train_data)
cat(paste("RMSE: ", RMSE(predictions, train$SalePrice)))

```


